### ISSUE TITLE
Create a summary page for the CSV conversion/import

### ISSUE THREAD

**Issue by GitMurf** [GitMurf/csv-to-roam-table-md#12]
Finally, if you want to go hog wild, you could create a summary page for the CSV converesion to markdown itself as a markdown page , eg 

"CSV Conversion-Date-Filename" as the page name
* "[[CSV filename]] imported/converted on [[conversion or import date]], creating n records/pages of [[page type]].  
List of all pages imported/converted
   * [[Page 1 title]]
   * [[Page ... title]]
   * [[Page n title]]

BTW, this summary page is not necessary, for me just would be nice.

_Originally posted by @phhq in https://github.com/GitMurf/csv-to-roam-table-md/issues/1#issuecomment-619412895_

**Comment by GitMurf** [comment]
This summary page should also be like a "Log" too. Basically everything the script is doing should be recorded here so before you import your pages to Roam you can review this Summary/Log to see what all the script did and what pages/attributes/data will be added to Roam. Then when in Roam this summary/log page will be great to see everything you did with this import and be able to quickly jump to each of the pages you created.

**Comment by phhq** [comment]
yes

**Comment by GitMurf** [comment]
Before getting all those scenarios/options integrated what I am doing from day 1 is creating that Summary type page you posted an idea about and am also using that as like a “Log” to track everything the script does. That way even before trying to replace or merge attributes with ones already in current pages, I will have the log file flag which pages there are potential conflicts with if the page already exists and if a particular attribute already exists on that page. That way you can quickly use the Logging in the summary page in Roam to go to any of the pages with duplicate attributes and manually update them in the meantime.

**Comment by phhq** [comment]
This is going to be quite powerful. I'm sure the #roamcult will enjoy.  Thank you for building this.

**Comment by GitMurf** [comment]
List of things to do for this request:

- [x] Create summary page (e.g., [[csv-import]] - locations.csv_2020_04_26-18_19_03.md)
- [x] Creation date attribute
- [x] Other attributes like Filename, Time created, CSV Type
- [x] Import stats like: "creating n records/pages"
- [x] Create log listing every action taken
- [x] Log: Attributes added
- [x] Log: Pages created
- [x] List all the pages created from rows and first column of CSV
- [x] Organize the pages in the summary page in a useful way
